CREATE TABLE LongListofSuspects (
    `Name` VARCHAR(51) CHARACTER SET utf8,
    `Sex` VARCHAR(6) CHARACTER SET utf8,
    `Hair` VARCHAR(6) CHARACTER SET utf8,
    `Eyes` VARCHAR(5) CHARACTER SET utf8,
    `Height` VARCHAR(7) CHARACTER SET utf8,
    `Build` VARCHAR(6) CHARACTER SET utf8,
    `Finger_Print` VARCHAR(6) CHARACTER SET utf8,
    `Glasses` VARCHAR(3) CHARACTER SET utf8
);
INSERT INTO LongListofSuspects VALUES ('Adam Baum','Male','Grey','Brown','Short','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Adam Zapel','Male','Brown','Brown','Average','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Al Bino','Male','Grey','Green','Short','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Al Dente','Male','Red','Brown','Tall','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Al Fresco','Male','Blonde','Brown','Average','Thin','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Al K. Seltzer','Male','Blonde','Brown','Short','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Allen Wrench','Male','Brown','Brown','Average','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Amanda Lynn','Female','Black','Brown','Average','Medium','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Andy Friese','Male','Brown','Green','Average','Wide','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Anita Job','Female','Red','Brown','Average','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Anna Conda','Female','Brown','Blue','Average','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Anna Graham','Female','Grey','Brown','Average','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Anna Prentice','Female','Brown','Brown','Average','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Anna Recksiek','Female','Red','Green','Average','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Anna Sasin','Female','Grey','Brown','Tall','Medium','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Anne Teak','Female','Black','Brown','Average','Thin','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Anne Ville','Female','Grey','Brown','Average','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Annie Howe','Female','Brown','Brown','Tall','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('April May','Female','Blond','Brown','Average','Medium','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('April Schauer','Female','Brown','Blue','Short','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Armand Hammer','Male','Red','Brown','Average','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Art Major','Male','Blonde','Blue','Average','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('B.A. Ware','Male','Blonde','Brown','Average','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Barb Dwyer','Female','Black','Blue','Short','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Barb E. Dahl','Female','Blonde','Brown','Average','Thin','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Barbara Seville','Female','Blonde','Blue','Short','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Barry Cade','Male','Blonde','Blue','Average','Thin','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Barry Medeep','Male','Blonde','Brown','Average','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Bea Gone','Male','Grey','Brown','Tall','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Bea Minor','Female','Blonde','Brown','Average','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Biff Wellington','Male','Brown','Blue','Average','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Bill Board','Male','Black','Green','Tall','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Bill Ding','Male','Red','Blue','Average','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Bill Dollar','Male','Red','Brown','Average','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Bill Foldes','Male','Blonde','Blue','Short','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Bill Loney','Male','Blond','Brown','Average','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Bill Payer','Male','Grey','Green','Tall','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Bob Forapples','Male','Brown','Brown','Average','Wide','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Bob Katz','Male','Grey','Brown','Average','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Bob Sledd','Male','Black','Brown','Short','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Bonnie Ann Clyde','Female','Red','Blue','Average','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Brighton Early','Female','Grey','Brown','Average','Thin','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Brock Lee','Female','Grey','Blue','Tall','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Brooke Trout','Female','Brown','Brown','Tall','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Bud Light','Male','Black','Green','Tall','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('C. Senor','Male','Black','Brown','Tall','Thin','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('C. Worthy','Male','Blond','Brown','Tall','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Cam Payne','Male','Grey','Brown','Average','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Candy Barr','Female','Red','Blue','Tall','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Candy Graham','Female','Black','Brown','Average','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Cara Sterio','Female','Red','Green','Tall','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Cara Van','Female','Blond','Green','Short','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Carrie Meback','Female','Red','Brown','Average','Thin','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Carrie Oakey','Female','Grey','Blue','Average','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Charity Case','Female','Black','Blue','Average','Thin','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Cheri Pitts','Female','Red','Brown','Tall','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Chip Munk','Male','Blonde','Brown','Short','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Chris Coe','Male','Blond','Blue','Tall','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Chris Cross','Male','Brown','Blue','Average','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Chris Ko','Male','Grey','Blue','Average','Thin','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Chris P. Bacon','Male','Grey','Brown','Average','Wide','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Chuck Waggon','Male','Red','Brown','Tall','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Claire Annette Reed','Female','Red','Blue','Average','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Constance Noring','Female','Blonde','Green','Short','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Cora Gated','Female','Grey','Blue','Short','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Corey Ander','Female','Black','Brown','Tall','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Corey O. Graff','Female','Grey','Blue','Average','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Count Dunn','Female','Black','Brown','Tall','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Crystal Ball','Female','Brown','Brown','Tall','Thin','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Crystal Claire Waters','Female','Black','Brown','Average','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('D. Kay, DDS','Male','Black','Brown','Short','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('D. Liver','Male','Grey','Brown','Average','Medium','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Dan D. Lyons','Male','Grey','Brown','Short','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Dan Druff','Male','Blonde','Brown','Average','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Dan Druff','Male','Red','Brown','Average','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Dan Saul Knight','Male','Red','Brown','Average','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Darren Deeds','Male','Grey','Green','Average','Wide','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Dinah Soares','Female','Blonde','Brown','Average','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Doris Schutt','Female','Blonde','Brown','Average','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Doug Graves','Male','Grey','Blue','Tall','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Doug Hole','Male','Grey','Blue','Average','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Doug Witherspoon','Male','Blonde','Blue','Average','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Douglas Furr','Male','Blond','Blue','Average','Thin','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Dr. E. Ville','Male','Brown','Blue','Short','Thin','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Dr. I. Ball (optometrist)','Male','Brown','Green','Average','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Dr. Kauff','Male','Red','Brown','Average','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Dr. Looney - a psychiatrist of course!','Female','Blonde','Brown','Average','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Dr. Payne (plastic surgeon in Sandusky, OH)','Female','Red','Blue','Short','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Dr. Slaughter','Female','Blonde','Brown','Average','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Dr. Surgeon (another real doctor from Stamford, CT)','Female','Brown','Green','Average','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Duane Pipe','Male','Blonde','Green','Average','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Dusty Carr','Male','Grey','Brown','Average','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Earl E. Bird','Male','Brown','Brown','Tall','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Earl Lee Riser','Male','Brown','Blue','Average','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Easton West','Male','Blonde','Blue','Average','Medium','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Ella Vader','Female','Red','Brown','Short','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Emma Royds','Female','Grey','Blue','Short','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Ethyl Gass','Female','Red','Brown','Short','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Evan Keel','Male','Blonde','Brown','Average','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Faith Christian','Female','Grey','Brown','Tall','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Father A. Long','Male','Brown','Brown','Short','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Ferris Wheeler','Male','Blonde','Blue','Average','Thin','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Flint Sparks','Male','Red','Brown','Short','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Ford Parker','Male','Blonde','Blue','Average','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Forrest Green','Male','Blonde','Brown','Tall','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Foster Child','Male','Black','Brown','Tall','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Frank Enstein','Male','Grey','Blue','Average','Thin','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Frank Furter','Male','Blond','Brown','Short','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Gail Force','Female','Red','Brown','Tall','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Gene Poole','Male','Grey','Brown','Average','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Gil Fish','Male','Red','Green','Average','Wide','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Ginger Snapp','Female','Red','Brown','Average','Medium','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Harry Caray','Male','Red','Brown','Average','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Harry Knuckles','Male','Grey','Brown','Average','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Hazle Nutt','Female','Blonde','Green','Tall','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Heidi Clare','Female','Red','Brown','Tall','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Herb Farmer','Male','Brown','Brown','Short','Wide','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Holly Day','Female','Brown','Blue','Tall','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Holly McRell','Female','Black','Brown','Average','Medium','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Honey Bee','Female','Brown','Brown','Short','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Howie Doohan','Male','Brown','Brown','Average','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Hy Price','Female','Grey','Brown','Average','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('I. Lasch','Female','Black','Brown','Average','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('I.D. Clair','Female','Blonde','Brown','Short','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('I.M. Boring','Male','Brown','Brown','Average','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Iona Ford','Female','Blonde','Brown','Average','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Iona Stonehouse','Female','Blonde','Brown','Average','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Isadore Bell','Female','Grey','Brown','Average','Wide','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Ivan Oder','Male','Black','Brown','Short','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Ivy Leage','Female','Grey','Brown','Tall','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Jack Enjill','Male','Blond','Brown','Tall','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Jack Pott','Male','Grey','Green','Average','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Jacklyn Hyde','Female','Red','Blue','Short','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Jay Bird','Male','Red','Brown','Average','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Jay Walker','Male','Blonde','Blue','Tall','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Jean Poole','Female','Red','Brown','Average','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Jed Dye','Male','Grey','Green','Average','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Jerry Atrick','Male','Black','Brown','Average','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Jerry Mander','Male','Brown','Brown','Short','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Jim Laucher','Male','Brown','Green','Tall','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Jim Shu','Male','Blond','Blue','Average','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Jo King','Male','Red','Brown','Short','Medium','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Joe Kerr','Male','Red','Green','Average','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Joy Kil','Female','Black','Brown','Average','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('June Bugg','Female','Grey','Brown','Average','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Justin Hale ','Male','Blonde','Brown','Average','Wide','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Kandi Apple','Female','Brown','Brown','Average','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Kay Bull','Female','Black','Green','Average','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Kelly Green','Female','Red','Brown','Average','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Kent C. Strait','Male','Black','Brown','Average','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Kenya Dewit','Female','Blonde','Brown','Short','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Kerry Oki','Male','Red','Blue','Average','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('King Queene','Male','Red','Brown','Average','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Kitty Litter','Female','Blond','Brown','Average','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Lance Boyle','Male','Grey','Brown','Average','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Laura Norder','Female','Brown','Blue','Short','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Leigh King','Female','Blonde','Green','Tall','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Les Moore','Male','Blond','Brown','Average','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Lewis N. Clark','Male','Black','Brown','Average','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Lily Pond','Female','Brown','Brown','Average','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Lisa Honda','Female','Grey','Brown','Average','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Liv Long','Female','Grey','Blue','Average','Medium','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Lois Price','Male','Blond','Brown','Tall','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Lou Pole','Male','Red','Brown','Tall','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Lou Zar','Male','Blonde','Green','Average','Wide','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Luckey Chance','Male','Black','Brown','Average','Thin','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Lucy Fer','Male','Red','Green','Average','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Luke Warm','Male','Grey','Brown','Average','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Lynn O. Liam','Female','Black','Blue','Tall','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('M. Balmer','Female','Blonde','Brown','Short','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Manny Kinn','Male','Grey','Brown','Short','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Mark Papers','Male','Brown','Brown','Average','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Mark Skid','Male','Black','Blue','Average','Thin','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Marlon Fisher','Male','Red','Brown','Short','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Marsha Dimes','Female','Black','Brown','Average','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Marsha Mellow','Female','Blonde','Green','Average','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Marshall Law','Male','Grey','Brown','Average','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Marty Graw','Male','Brown','Brown','Tall','Medium','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Mary A. Richman','Female','Black','Brown','Average','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Mary Annette Woodin','Female','Grey','Blue','Tall','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Mary Christmas','Female','Grey','Blue','Short','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Mary Mee','Female','Blond','Blue','Average','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Matt Tress','Male','Grey','Green','Short','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Maude L.T. Ford','Female','Red','Brown','Average','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Max Power','Male','Red','Blue','Average','Thin','Loops','No');
INSERT INTO LongListofSuspects VALUES ('May Day','Female','Black','Blue','Average','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('May Furst','Female','Black','Blue','Average','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Mel Loewe','Female','Brown','Brown','Short','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Melba Crisp','Female','Grey','Brown','Tall','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Melody Music','Female','Blonde','Brown','Tall','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Mia Hamm','Female','Blonde','Brown','Short','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Mike Easter','Male','Grey','Green','Average','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Mike Raffone','Male','Black','Brown','Tall','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Mike Reinhart','Male','Black','Brown','Short','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Mike Rotch','Male','Grey','Brown','Average','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Mike Stand','Male','Blond','Brown','Average','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Milly Graham','Female','Red','Brown','Tall','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Minny van Gogh','Male','Black','Brown','Short','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Missy Sippy','Female','Red','Brown','Average','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Misty Waters','Female','Blond','Green','Average','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Moe B. Dick','Male','Blonde','Brown','Average','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Muddy Waters','Male','Grey','Blue','Average','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Myles Long','Male','Grey','Brown','Short','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Neil Down','Male','Brown','Brown','Average','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Neil McNeil','Male','Blonde','Brown','Tall','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Nick O. Time','Male','Blond','Brown','Average','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Noah Lott','Male','Red','Blue','Tall','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Olive Branch','Female','Black','Brown','Short','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Olive Green','Female','Black','Blue','Tall','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Olive Hoyl','Female','Brown','Brown','Tall','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Olive Yew','Female','Blonde','Blue','Average','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Oliver Sutton','Female','Red','Blue','Average','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Ophelia Payne','Female','Blonde','Brown','Average','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Oren Jellow','Male','Brown','Brown','Average','Medium','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Oscar Award','Male','Brown','Green','Average','Wide','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Otto Graf','Male','Red','Green','Average','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Owen Cash','Male','Brown','Blue','Average','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Owen Money','Male','Blonde','Brown','Tall','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('P. Brain','Male','Red','Blue','Average','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Paige Turner','Female','Brown','Brown','Tall','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Park A. Studebaker','Male','Blond','Brown','Average','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Parker Carr','Male','Black','Blue','Average','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Pat Downe','Female','Black','Brown','Average','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Patience Wait','Female','Black','Green','Average','Wide','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Patty Cakes','Female','Grey','Brown','Average','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Patty O''Furnature','Female','Blond','Brown','Short','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Pearl Button','Female','Red','Brown','Average','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Pearl E. Gates','Female','Black','Green','Short','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Peg Legge','Female','Red','Brown','Average','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Penny Lane','Female','Brown','Blue','Tall','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Penny Loafer','Female','Black','Green','Average','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Pepe Roni','Male','Red','Blue','Average','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Peri Winkle','Male','Blonde','Brown','Average','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Pete Moss','Male','Grey','Brown','Short','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Phil Graves','Male','Blonde','Brown','Tall','Medium','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Phil O''Dendron','Male','Brown','Brown','Average','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Phil Rupp','Male','Blonde','Brown','Average','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Phillip D. Bagg','Male','Blonde','Brown','Average','Wide','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Pierce Deere','Male','Red','Brown','Short','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Pierce Hart','Male','Brown','Blue','Tall','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Polly Ester','Female','Grey','Brown','Short','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Post, Mark','Male','Brown','Blue','Average','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Price Wright','Male','Black','Brown','Tall','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('R. M. Pitt','Male','Red','Blue','Short','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Raney Schauer','Female','Red','Brown','Average','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Ray Gunn','Male','Brown','Brown','Average','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Ray Zenz','Male','Black','Brown','Average','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Raynor Schein','Male','Brown','Brown','Average','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Reid Enright','Male','Brown','Blue','Average','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Rhea Curran','Male','Red','Green','Short','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Rhoda Booke','Female','Blond','Brown','Short','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Rich Feller','Male','Red','Brown','Tall','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Rick O''Shea','Male','Blond','Green','Average','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Rick Shaw','Male','Red','Brown','Average','Medium','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Rip Torn','Male','Brown','Green','Short','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Rita Buch','Female','Blonde','Brown','Average','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Robin Andis Merryman','Male','Brown','Brown','Average','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Robin Banks','Female','Brown','Brown','Average','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Rocky Rhoades','Male','Black','Blue','Average','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Rod N. Reel','Male','Black','Brown','Average','Medium','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Roman Holiday','Male','Brown','Brown','Average','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Rose Gardner','Female','Grey','Blue','Average','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Rowan Boatman','Male','Brown','Brown','Short','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Royal Payne','Male','Black','Brown','Average','Wide','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Russell Leeves','Male','Black','Brown','Average','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Russell Sprout','Male','Brown','Green','Average','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Rusty Fossat','Male','Grey','Brown','Tall','Medium','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Rusty Keyes','Male','Grey','Brown','Average','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Sal A. Mander','Male','Grey','Blue','Average','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Sandy C. Shore','Female','Black','Brown','Average','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Sarah Bellum','Female','Black','Blue','Average','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Shanda Lear','Female','Grey','Green','Tall','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Sharon A. Burger','Female','Grey','Brown','Short','Medium','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Sheila Blige','Female','Grey','Brown','Tall','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Sherry Wine','Female','Grey','Blue','Average','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Skip Roper','Male','Blond','Blue','Average','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Sno White','Female','Brown','Blue','Average','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Sonny Day','Male','Red','Blue','Tall','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Stan Still','Male','Blonde','Blue','Average','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Stanley Cupp','Male','Blonde','Brown','Tall','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Starr Lett','Female','Black','Brown','Short','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Steve Adore','Male','Brown','Brown','Short','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Sue Flay','Female','Brown','Brown','Tall','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Sue Render','Female','Black','Brown','Tall','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Sue Ridge','Female','Blonde','Blue','Short','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Sue Yu','Female','Grey','Brown','Average','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Summer Camp','Female','Brown','Brown','Average','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Tad Moore','Male','Blonde','Green','Average','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Tad Pohl','Male','Grey','Brown','Tall','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Tamara Knight','Female','Blonde','Blue','Tall','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Tanya Hyde','Female','Black','Blue','Short','Thin','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Ted E. Baer','Male','Brown','Brown','Average','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Terry Achey','Female','Grey','Green','Average','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Terry Bull','Female','Brown','Blue','Tall','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Terry Cloth','Female','Black','Brown','Average','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Tim Burr','Male','Blonde','Brown','Short','Medium','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Tim Burr','Male','Blonde','Brown','Average','Thin','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Tish Hughes','Female','Blond','Blue','Short','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Tom Katt','Male','Grey','Brown','Average','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Tom Katt','Male','Red','Brown','Short','Wide','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Tom Morrow','Male','Grey','Brown','Average','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Tommy Gunn','Male','Red','Brown','Average','Medium','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Tommy Hawk','Male','Blonde','Brown','Average','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Trina Woods','Female','Blond','Brown','Average','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Ty Coon','Male','Grey','Brown','Average','Wide','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Ty Ping','Male','Blonde','Blue','Tall','Medium','Arches','No');
INSERT INTO LongListofSuspects VALUES ('Val Entine','Female','Brown','Brown','Average','Medium','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Viola Solo','Female','Blond','Brown','Average','Wide','Whorls','No');
INSERT INTO LongListofSuspects VALUES ('Virginia Beach','Female','Red','Brown','Average','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Walter Melon','Male','Brown','Blue','Short','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Wanda Rinn','Female','Black','Blue','Average','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Warren Peace','Male','Red','Blue','Average','Medium','Loops','No');
INSERT INTO LongListofSuspects VALUES ('Warren T.','Male','Brown','Brown','Average','Medium','Loops','Yes');
INSERT INTO LongListofSuspects VALUES ('Will Power','Male','Grey','Blue','Average','Thin','Whorls','Yes');
INSERT INTO LongListofSuspects VALUES ('Will Wynn','Male','Black','Brown','Short','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Willie Waite','Male','Red','Brown','Short','Medium','Arches','Yes');
INSERT INTO LongListofSuspects VALUES ('Winsom Cash','Male','Black','Brown','Average','Medium','Loops','No');
